routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



/*
 ---------------------------------------------------------
  ROUTES :
 ---------------------------------------------------------
*/

/*
  ROUTE PAR DEFAUT
  PATERN: /
  CTRL: Pages
  ACTION: index
*/
Route::get('/', 'PagesController@show')->defaults('page', 1)->name('app');

/*
  ROUTE DETAILS D'UNE PAGE
  PATERN: /pages/id/slug.html
  CTRL: Pages
  ACTION: show
*/
Route::get('/pages/{page}/{slug}.html', 'PagesController@show')
      ->where([
          'pages' => '[1-9][0-9]*',
          'slug' => '[a-z0-9][a-z0-9\-]*[a-z0-9]'
      ])
      ->name('pages.show');


/*
  ROUTES DES CREATURES
*/
Route::prefix('creatures')->name('creatures.')->group(function (){
  /*
    ROUTE DETAILS D'UNE CREATURE
    PATERN: /creatures/id/slug.html
    CTRL: CreaturesController
    ACTION: show
  */
  Route::get('/{creature}/{slug}.html', 'CreaturesController@show')
        ->where([
              'creature' => '[1-9][0-9]*',
              'slug' => '[a-z0-9][a-z0-9\-]*[a-z0-9]'
            ])
        ->name('show');
});


/*
  ROUTE DES FILMS
*/
Route::prefix('films')->name('films.')->group(function (){
  /*
    ROUTE DETAILS D'UN FILM
    PATERN: /films/id/slug.html
    CTRL: FilmsController
    Action: show
  */
  Route::get('/{film}/{slug}.html', 'FilmsController@show')
  ->where([
        'film' => '[1-9][0-9]*',
        'slug' => '[a-z0-9][a-z0-9\-]*[a-z0-9]'
      ])
  ->name('show');

  /*
    FORMULAIRE D'AJOUT D'UN FILM
    PATTERN: /films/create/slug.html
    CTRL: Films
    ACTION: create
  */
    Route::get('/create/{slug}.html','FilmsController@create')
        ->where([
                'slug' => '[a-z0-9][a-z0-9\-]*[a-z0-9]'
              ])
          ->name('create');

  /*
    INSERT D'UN FILM
    PATTERN: /films [POST]
    CTRL: Films
    ACTION: store
  */
    Route::post('/','FilmsController@store')
          ->name('store');

  /*
    FORMULAIRE DE L'EDIT D'UN FILM
    PATTERN: /films/id/edit
    CTRL: Films
    ACTION: edit
   */
    Route::get('/{film}/edit/{slug}.html','FilmsController@edit')
           ->where([
              'film' => '[1-9][0-9]*',
              'slug' => '[a-z0-9][a-z0-9\-]*[a-z0-9]'
             ])
          ->name('edit');

  /*
    UPDATE D'UN FILM
    PATTERN: /films/{films} [PATCH]
    CTRL: Films
    ACTION: update
   */
    Route::patch('/{film}','FilmsController@update')
           ->where([
              'film' => '[1-9][0-9]*'
             ])
          ->name('update');

  /*
    ROUTE DE LA SUPPRESSION D'UN FILM
    PATTERN: /films/{film} [DELETE]
    CTRL: Films
    ACTION: destroy
   */
    Route::delete('/{film}','FilmsController@destroy')
           ->where([
              'film' => '[1-9][0-9]*'
             ])
          ->name('destroy');
});

/*
  ROUTE DETAILS D'UN TAG
  PATTERN: /tags/id/slug.html
  CTRL: Tags
  ACTION: show
*/
Route::get('/tags/{tag}/{slug}.html', 'TagsController@show')
      ->where([
            'tag' => '[1-9][0-9]*',
            'slug' => '[a-z0-9][a-z0-9\-]*'
      ])
      ->name('tags.show');

/*
  ROUTE DE LA RECHERCHE
  PATTERN: /search
  CTRL: Creatures
  ACTION: search
*/
Route::get('/search', 'CreaturesController@search')
      ->name('creatures.search');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CreaturesController.php
<?php
   namespace App\Http\Controllers;

   use Illuminate\Support\Facades\View;
   use App\Http\Models\Creature;
   use Illuminate\Http\Request;
   use Illuminate\Support\Facades\DB;

   class CreaturesController extends Controller {

     /**
      * Affiche le detail d'une créature
      *@param Creature $creature
      *@return vue creatures.show
      */

     public function show($id){
       $creature = Creature::find($id);
       return View::make('creatures.show',compact('creature'));
     }


     /**
     *Affiche le resultat de la recherche
     *@param Request $request
     *@return vue creatures.search-results
     */
     public function search(Request $request) {
       $request->validate([
         'query' => 'required|min:1'
       ]);
       $query = $request->input('query');
       $creatures = Creature::where('nom', 'LIKE', "%$query%")->get();
       return View::make('creatures.search')->with('creatures', $creatures);
     }
   }

app/Http/Controllers/FilmsController.php
<?php
   namespace App\Http\Controllers;

   use Illuminate\Support\Facades\View;
   use App\Http\Models\Film;
   use App\Http\Models\Page;
   use Illuminate\Http\Request;
   use Illuminate\Support\Facades\DB;


   class FilmsController extends Controller {

     public function show(Film $film) {
       return View::make('films.show',compact('film'));
     }

     public function create() {
       return View::make('films.create');
     }

     public function store(Request $request) {
       Film::create($request->all());
       return redirect()->route('pages.show', ['page' => 2, 'slug' => 'films']);
     }

     public function edit(Film $film) {
       return View::make('films.edit', compact('film'));
     }

     public function update(Request $request, Film $film) {
       $film->update($request->all());
       return redirect()->route('pages.show', ['page' => 2, 'slug' => 'films']);
     }

     public function destroy(Film $film) {
       $film->destroy($film->id);
       return redirect()->route('pages.show', ['page' => 2, 'slug' => 'films']);
     }

   }

app/Http/Controllers/PagesController.php
<?php
namespace App\Http\Controllers;

use Illuminate\Support\Facades\View;
use App\Http\Models\Page;
use App\Http\Models\Creature;
use App\Http\Models\Film;
use Illuminate\Support\Facades\DB;

class PagesController extends Controller {

  /**
   * Détails de la pages $id
   * @param integer $id [id de la page à afficher]
   *@return View       [Vue pages/show.blade.php]
  */

  public function show($id = 1){
    $page = Page::find($id);
    if ($page->id === 1):
      $creatures = Creature::orderBy('created_at', 'desc')->take(2)->get();
      return View::make('pages.show', compact('page', 'creatures'));
    elseif ($page->id === 2):
      $films = Film::orderBy('created_at', 'desc')->get();
      return View::make('pages.show', compact('page', 'films'));
    elseif ($page->id === 3):
      $creatures = Creature::orderBy('created_at', 'desc')->get();
      return View::make('pages.show', compact('page', 'creatures'));
    endif;
    return View::make('pages.show', compact('page'));

    /*$pages = Page::all();
    return View::make('pages.show',['pages' => $pages]);
    */
  }
}

app/Http/Controllers/TagsController.php
<?php
namespace App\Http\Controllers;

use Illuminate\Support\Facades\View;
use App\Http\Models\Tag;

class TagsController extends Controller {

    public function show(Tag $tag) {
      return View::make('tags.show', compact('tag'));
    }

}

resources/views/creatures/index.blade.php
{{--
  ./resources/views/creatures/index.blade.php
  Liste des créatures
  vairables disponibles :
      - $creatures
 --}}

@foreach ($creatures as $creature)
  <!-- Project One -->
  <div class="row">
    <div class="col-md-4">
      <a href="#">
        <img class="img-fluid rounded mb-3 mb-md-0" src="{{ asset('images/'.$creature->image) }}" alt="">
      </a>
    </div>
    <div class="col-md-8">
      <h3>{{ $creature->nom }}</h3>
      <p class="lead">
        dans
        <a href="artiste_details.html">Ze craignos monster</a>
        le {{ \Carbon\Carbon::parse ($creature->created_at)->format('d-m-Y')}}
      </p>
      <p>{{ $creature->texteLead}}</p>
      <a class="btn btn-primary" href="{{ URL::route('creatures.show', [
          'creature' => $creature->id,
          'slug'     => Str::slug($creature->nom)
        ]) }}">
        Voir la créature
      </a>
      <hr/>
      <ul class="list-inline tags">
        @foreach ($creature->tags as $tag)
          <li>
            <a href="{{ URL::route('tags.show', [
              'tag'  => $tag->id,
              'slug' => Str::slug($tag->nom, '-')
              ]) }}" class="btn btn-default btn-xs">
              {{ $tag->nom }}
            </a>
          </li>
        @endforeach
      </ul>
    </div>
  </div>
  <!-- /.row -->
  <hr>
@endforeach

resources/views/creatures/search.blade.php
{{--
  ./resources/views/creatures/search-results.blade.php
  variables disponibles :

 --}}
@extends('template.app')

@section('titre')
  Les Créatures du Futur
@endsection

@section('content1')
<!-- Page Heading -->

<!-- Title -->
<h1 class="mt-4">
  Résultats de votre recherche :
    <small>{{ request()->input('query') }}</small>
</h1>

<hr>

  @foreach ($creatures as $creature)
    <!-- Project One -->
    <div class="row">
      <div class="col-md-4">
        <a href="#">
          <img class="img-fluid rounded mb-3 mb-md-0" src="{{ asset('images/'.$creature->image) }}" alt="">
        </a>
      </div>
      <div class="col-md-8">
        <h3>{{ $creature->nom }}</h3>
        <p class="lead">
          dans
          <a href="artiste_details.html">Ze craignos monster</a>
          le {{ \Carbon\Carbon::parse ($creature->created_at)->format('d-m-Y')}}
        </p>
        <p>{{ $creature->texteLead}}</p>
        <a class="btn btn-primary" href="{{ URL::route('creatures.show', [
            'creature' => $creature->id,
            'slug'     => Str::slug($creature->nom)
          ]) }}">
          Voir la créature
        </a>
        <hr/>
        <ul class="list-inline tags">
          @foreach ($creature->tags as $tag)
            <li>
              <a href="{{ URL::route('tags.show', [
                'tag'  => $tag->id,
                'slug' => Str::slug($tag->nom, '-')
                ]) }}" class="btn btn-default btn-xs">
                {{ $tag->nom }}
              </a>
            </li>
          @endforeach
        </ul>
      </div>
    </div>
    <!-- /.row -->
    <hr>
  @endforeach

@endsection

resources/views/creatures/show.blade.php
{{--
  ./resources/views/creatures/show.blade.php
  variables disponibles :
      - $creature
 --}}
@extends('template.app')

@section('titre')
{{ $creature->nom }}
@endsection

@section('content1')
     <!-- Page Heading -->

     <!-- Title -->
     <h1 class="mt-4">{{ $creature->nom }}</h1>
     <p class="lead">
       dans
       <a href="artiste_details.html">Film 1</a>
       le {{ \Carbon\Carbon::parse ($creature->created_at)->format('d-m-Y')}}
     </p>

     <hr>

     <!-- Project One -->
     <div class="row">
       <div class="col-md-6">
         <a href="#">
           <img class="img-fluid rounded mb-3 mb-md-0" src="{{ asset('images/'.$creature->image) }}" alt="">
         </a>
       </div>
       <div class="col-md-6">
         <p class="lead">{{ $creature->texteLead}}</p>
         <hr/>
         <p>{{ $creature->texteSuite}}</p>

         <hr/>
         <ul class="list-inline tags">
           @foreach ($creature->tags as $tag)
             <li>
               <a href="{{ URL::route('tags.show', [
                 'tag'  => $tag->id,
                 'slug' => Str::slug($tag->nom, '-')
                 ]) }}" class="btn btn-default btn-xs">
                 {{ $tag->nom }}
               </a>
             </li>
           @endforeach
         </ul>
       </div>
     </div>
     <!-- /.row -->
     <hr>
@endsection

resources/views/films/create.blade.php
{{--
  ./resources/views/tags/create.blade.php
 --}}

 @extends('template.app')

 @section('titre')
   Les Créatures du Futur
 @endsection

 @section('content1')
   <h1 class="mt-4">Ajouter un Film</h1>

   <form method="POST" action="{{ route('films.store') }}">
    @csrf
    <div class="form-group">
      <label for="">Titre</label>
      <input type="text" class="form-control" name="titre"/>
    </div>
    <div class="form-group">
      <label for="">Synopsis</label>
      <textarea rows="8" cols="80" class="form-control" name="synopsis"></textarea>
    </div>
    <div class="form-group">
      <input type="submit" class="btn btn-primary"/>
    </div>
   </form>
   <!-- /.row -->
   <hr>
 @endsection

resources/views/films/edit.blade.php
{{--
  ./resources/views/films/edit.blade.php
  Variable disponible:
    - $film Film
 --}}

 @extends('template.app')

 @section('titre')
   Les Créatures du Futur
 @endsection

 @section('content1')
<h1 class="mt-4">Modifier un Film</h1>

<form method="POST" action="{{ route('films.update', $film->id) }}">
  @csrf
    {{ method_field('PATCH') }}
  <div class="form-group">
    <label for="">Titre</label>
    <input type="text" class="form-control" value="{{ $film->nom }}" name="titre"/>
  </div>
  <div class="form-group">
    <label for="">Synopsis</label>
    <textarea rows="8" cols="80" class="form-control" name="synopsis"></textarea>
  </div>
  <div class="form-group">
    <input type="submit" class="btn btn-primary" />
  </div>
</form>

<!-- /.row -->
<hr>
@endsection

resources/views/films/index.blade.php
{{--
  ./resources/views/films/index.blade.php
  Liste des films
  vairables disponibles :
      - $films
 --}}

@foreach ($films as $film)
<!-- Project One -->
<div class="row">
  <div class="col-md-4">
    <a href="#">
      <img class="img-fluid rounded mb-3 mb-md-0" src="{{ asset('images/'.$film->image) }}" alt="">
    </a>
  </div>
  <div class="col-md-8">
    <h3>{{ $film->titre }}</h3>
    <p>{{ $film->synopsis}}</p>
    <a class="btn btn-primary" href="{{ URL::route('films.show', [
      'film'  =>  $film->id,
      'slug'  => Str::slug($film->titre)
      ]) }}">
      Voir les détails du film
    </a>
    <hr/>
  </div>
</div>
<hr/>
@endforeach

resources/views/films/show.blade.php
{{--
  ./resources/views/films/show.blade.php
  variables disponibles :
      - $film
 --}}
 @extends('template.app')

 @section('titre')
   Les Films
 @endsection

 @section('content1')
    <!-- Page Heading -->

    <!-- Title -->
    <h1 class="mt-4">{{ $film->titre }}</h1>

    <hr>

    <!-- Project One -->
    <div class="row">
      <div class="col-md-4">
        <a href="#">
          <img class="img-fluid rounded mb-3 mb-md-0" src="{{ asset('images/'.$film->image) }}" alt="">
        </a>
      </div>
      <div class="col-md-8">
        <p class="lead">{{ $film->synopsis }}</p>
        <hr/>
        <h2>Créatures du film</h2>
        <ul>

          @foreach ($film->creatures as $creature)
            <li><a href="{{  URL::route('creatures.show', [
                'creature' => $creature->id,
                'slug'     => Str::slug($creature->nom)
              ]) }}">
              {{ $creature->nom }}
            </a>
          </li>
          @endforeach
        </ul>
        <hr/>
          <a class="btn btn-primary" href="{{ URL::route('films.edit',  [
              'film' => $film->id,
              'slug' => Str::slug($film->titre)
              ]) }}">Modifier</a>
          <form method="POST" action="{{ route('films.destroy', $film->id) }}" class="btn">
            {{ csrf_field() }}
            {{ method_field('DELETE') }}
            <div class="form-group">
              <input type="submit" class="btn btn-danger" value="Delete film">
            </div>
          </form>

        <hr />

      </div>
    </div>
    <!-- /.row -->
    <hr>
@endsection

resources/views/pages/_menu.blade.php
{{--
  ./resources/views/pages/_menu.blade.php
  variables disponibles :
      - $pages Pages
 --}}


<ul class="navbar-nav ml-auto">
  @foreach ($pages as $page)
    <li class="nav-item active">
      <a class="nav-link" href="{{ URL::route('pages.show', [
          'page' => $page->id,
          'slug' => Str::slug($page->titre)
          ]) }}">
        {{ $page->titre }}
      </a>
    </li>
  @endforeach
</ul>

resources/views/pages/show.blade.php
{{--
  ./resources/views/pages/show.blade.php
  variables disponibles :
      - $pages Page
      - Si $page-id =1 : $creatures
 --}}

 @extends('template.app')

 @section('titre')
   Les Créatures du Futur
 @endsection

 @section('content1')
   <!-- Page Heading -->
   <!-- Title -->
   <h1 class="mt-4">{{ $page->titre }}</h1>

   <hr>

   <!-- Post Content -->
   <p class="lead">{{ $page->texte }}</p>

   <hr>

<!-- Intégrations des vues complémentaires -->
   @if ($page->id === 1)
     <!-- Title -->
     <h2 class="mt-4">Dernieres créatures</h2>
     <hr>
     @include('creatures.index')
   @elseif ($page->id === 2)
     <a class="btn btn-primary" href="{{ URL::route('films.create', [
       'slug' => Str::slug($page->titre)
       ]) }}">Ajouter un film</a>
     <hr/>
     @include('films.index')
     <hr>
   @elseif ($page->id === 3)
     @include('creatures.index')
     <hr>
   @endif

 @endsection

resources/views/tags/_menu.blade.php
{{--
  ./resources/views/tags/menu.blade.php
  variables disponibles :
      - $tags Array(Tag)
 --}}

<h5 class="card-header">Tags</h5>
<div class="card-body">
  <div class="row">
    <div class="col-lg-12">
      <ul class="list-unstyled mb-0">
        @foreach ($tags as $tag)
          <li>
            <a href="{{ URL::route('tags.show', [
              'tag'  => $tag->id,
              'slug' => Str::slug($tag->nom, '-')
              ]) }}">
              {{ $tag->nom }}
            </a>
          </li>
        @endforeach
      </ul>
    </div>
  </div>
</div>

resources/views/tags/show.blade.php
{{--
  ./resources/views/tags/show.blade.php
  variables disponibles :
      - $tag Tag
 --}}

@extends('template.app')

@section('titre')
  Posts du tag {{ $tag->nom }}
@endsection

@section ('content1')
  <!-- Page Heading -->
  <!-- Title -->
  <h1 class="mt-4">{{ $tag->nom }}</h1>
  <p class="lead">Liste des créatures</p>

  <hr>

  @foreach ($tag->creatures as $creature)
    <!-- Project One -->
    <div class="row">
      <div class="col-md-4">
        <a href="#">
          <img class="img-fluid rounded mb-3 mb-md-0" src="{{ asset('images/'.$creature->image) }}" alt="">
        </a>
      </div>
      <div class="col-md-8">
        <h3>{{ $creature->nom }}</h3>
        <p class="lead">
          dans
          <a href="artiste_details.html">Ze craignos monster</a>
          le {{ \Carbon\Carbon::parse ($creature->created_at)->format('d-m-Y')}}
        </p>
        <p>{{ $creature->texteLead}}</p>
        <a class="btn btn-primary" href="{{ URL::route('creatures.show', [
            'creature' => $creature->id,
            'slug'     => Str::slug($creature->nom)
          ]) }}">
          Voir la créature
        </a>
        
        <hr/>

      </div>
    </div>
    <!-- /.row -->

    <hr>
  @endforeach

@endsection

resources/views/template/app.blade.php
{{--
  ./resources/views/template/app.blade.php
  Template général
 --}}

<!DOCTYPE html>
<html lang="en">
  <head>
    @include('template.partials._head')
  </head>
<body>

    <!-- Navigation -->
    @include('template.partials._nav')

    <!-- Page Content -->
    <div class="container">
      <div class="row">
        <!-- Post Content Column -->
        <div class="col-lg-8">

          @yield('content1')

        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">
          @include('template.partials._sidebar')
        </div>

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      @include('template.partials._footer')
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    @include('template.partials._scripts')
  </body>

</html>

resources/views/template/partials/_footer.blade.php
<div class="container">
  <p class="m-0 text-center text-white">Copyright &copy; IEPS 2017 <!-- | <a href="login.html">Administration</a>--></p>
</div>

resources/views/template/partials/_head.blade.php
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">

<title>Vintage Sci-Fi - @yield('titre')</title>

<!-- Bootstrap core CSS -->
<link href="{{ asset('vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="{{ asset('css/blog-post.css') }}" rel="stylesheet">

resources/views/template/partials/_nav.blade.php
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="#">Vintage Sci-Fi -   @yield('titre') </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      @include(
        'pages._menu',
        ['pages' => \App\Http\Models\Page::all()]
        )
    </div>
  </div>
</nav>

resources/views/template/partials/_scripts.blade.php
<script src="{{ asset('vendor/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

resources/views/template/partials/_sidebar.blade.php
<!-- Search Widget -->
<form action="{{ route('creatures.search') }}" method="get">
  <div class="card my-4">
    <h5 class="card-header">Rechercher une créature</h5>
    <div class="card-body">
      <div class="input-group">
        <input type="text" name="query" value="{{ request()->input('query') }}" class="form-control" placeholder="Mot-clé">
        <span class="input-group-btn">
          <button class="btn btn-secondary" type="submit">Go!</button>
        </span>
      </div>
    </div>
  </div>
</form>


<!-- Categories Widget -->
<div class="card my-4">
  @include('tags._menu')
</div>